export const authenUsers = [
    {
        influId: 1,
        email: "influ@test.com",
        password: "1234",
        accessToken: "token1",
        firstName: "influ",
        lastName: "001",
        profilePicture: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        facebook: "facebook.com/influencer",
        facebookFollower: 21515,
        instagram: "instagram.com/influencer",
        instagramFollower: 41316,
        x: "x.com/influencer",
        xFollower: 4887,
        tiktok: "tiktok.com/@influencer",
        tiktokFollower: 84659,
        categories: ["fashion", "lifestyle"],
        yourInfo: "กิน เที่ยว เล่นเกม หนัง",
        accountId: 1,
    },
    {
        influId: 2,
        email: "pin@test.com",
        password: "1234",
        accessToken: "token2",
        firstName: "Pin",
        lastName: "Natcha",
        facebook: "fb link",
        instagram: "ig link",
        profilePicture: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
        x: "x link",
        tiktok: "tiktok link",
        categories: ["fashion", "lifestyle"],
        accountId: 2,
    },
]
