
export const jobs = [
    {
        jobId: 1,
        title: "Fashion Blogger for Spring Collection",
        description: "Create posts and stories featuring the new Spring Collection.",
        category: "fashion",
        brand: "Urban Wear",
        income: 5000,
        brandImage: "https://example.com/urbanwear-logo.jpg",
        marketerId: 101,
        dueDate: "2025-04-01",
        influencerCount: 5,
        minimumFollower: 10000
    },
    {
        jobId: 2,
        title: "Tech Product Review for New Smartphone",
        description: "Review the latest smartphone model and create a video overview.",
        category: "tech",
        brand: "TechMart",
        income: 8000,
        brandImage: "https://example.com/techmart-logo.jpg",
        marketerId: 102,
        dueDate: "2025-03-15",
        influencerCount: 3,
        minimumFollower: 20000
    },
    {
        jobId: 3,
        title: "Beauty Influencer for Skincare Routine",
        description: "Promote a new skincare routine on Instagram.",
        category: "beauty",
        brand: "GlowSkincare",
        income: 6000,
        brandImage: "https://example.com/glowskincare-logo.jpg",
        marketerId: 103,
        dueDate: "2025-03-25",
        influencerCount: 7,
        minimumFollower: 15000
    },
    {
        jobId: 4,
        title: "Lifestyle Blogger for Eco-Friendly Products",
        description: "Write blogs and create content around eco-friendly home products.",
        category: "lifestyle",
        brand: "EcoHome",
        income: 4500,
        brandImage: "https://example.com/ecohome-logo.jpg",
        marketerId: 104,
        dueDate: "2025-04-05",
        influencerCount: 4,
        minimumFollower: 12000
    },
    {
        jobId: 5,
        title: "Food Vlogger for Vegan Recipes",
        description: "Create video content around easy and delicious vegan recipes.",
        category: "food",
        brand: "GreenPlate",
        income: 7000,
        brandImage: "https://example.com/greenplate-logo.jpg",
        marketerId: 105,
        dueDate: "2025-04-10",
        influencerCount: 6,
        minimumFollower: 18000
    },
    {
        jobId: 6,
        title: "Health Influencer for Fitness Challenge",
        description: "Promote a 30-day fitness challenge on social media.",
        category: "health",
        brand: "FitLife",
        income: 7500,
        brandImage: "https://example.com/fitlife-logo.jpg",
        marketerId: 106,
        dueDate: "2025-04-15",
        influencerCount: 10,
        minimumFollower: 25000
    },
    {
        jobId: 7,
        title: "Gaming Influencer for Live Streaming Event",
        description: "Host a live streaming event for a new game release.",
        category: "gaming",
        brand: "GameZone",
        income: 10000,
        brandImage: "https://example.com/gamezone-logo.jpg",
        marketerId: 107,
        dueDate: "2025-03-30",
        influencerCount: 2,
        minimumFollower: 50000
    },
    {
        jobId: 8,
        title: "Sports Influencer for New Workout Gear",
        description: "Review and promote new high-performance workout gear.",
        category: "sport",
        brand: "AthleX",
        income: 6000,
        brandImage: "https://example.com/athlex-logo.jpg",
        marketerId: 108,
        dueDate: "2025-04-08",
        influencerCount: 5,
        minimumFollower: 20000
    },
    {
        jobId: 9,
        title: "Fashion Influencer for Summer Trends",
        description: "Create content around upcoming summer fashion trends.",
        category: "fashion",
        brand: "TrendWear",
        income: 5500,
        brandImage: "https://example.com/trendwear-logo.jpg",
        marketerId: 109,
        dueDate: "2025-05-01",
        influencerCount: 4,
        minimumFollower: 15000
    },
    {
        jobId: 10,
        title: "Tech Reviewer for Latest Laptop Model",
        description: "Review and create content about the newest laptop.",
        category: "tech",
        brand: "CompPro",
        income: 9000,
        brandImage: "https://example.com/comppro-logo.jpg",
        marketerId: 110,
        dueDate: "2025-04-12",
        influencerCount: 3,
        minimumFollower: 30000
    },
    {
        jobId: 11,
        title: "Beauty Influencer for Makeup Tutorials",
        description: "Create makeup tutorials featuring the latest beauty products.",
        category: "beauty",
        brand: "BeautyGlow",
        income: 5800,
        brandImage: "https://example.com/beautyglow-logo.jpg",
        marketerId: 111,
        dueDate: "2025-04-20",
        influencerCount: 8,
        minimumFollower: 20000
    },
    {
        jobId: 12,
        title: "Lifestyle Blogger for Minimalist Living",
        description: "Create blogs and videos about the benefits of minimalist living.",
        category: "lifestyle",
        brand: "SimpleLife",
        income: 4000,
        brandImage: "https://example.com/simplelife-logo.jpg",
        marketerId: 112,
        dueDate: "2025-05-05",
        influencerCount: 3,
        minimumFollower: 10000
    },
    {
        jobId: 13,
        title: "Food Influencer for Quick Dinner Recipes",
        description: "Share easy and quick dinner recipes on social media.",
        category: "food",
        brand: "HomeChef",
        income: 5000,
        brandImage: "https://example.com/homechef-logo.jpg",
        marketerId: 113,
        dueDate: "2025-04-25",
        influencerCount: 6,
        minimumFollower: 12000
    },
    {
        jobId: 14,
        title: "Health Influencer for Yoga Series",
        description: "Host a yoga video series for beginners.",
        category: "health",
        brand: "ZenYoga",
        income: 7200,
        brandImage: "https://example.com/zenyoga-logo.jpg",
        marketerId: 114,
        dueDate: "2025-04-18",
        influencerCount: 4,
        minimumFollower: 17000
    },
    {
        jobId: 15,
        title: "Gaming Content Creator for Game Review",
        description: "Review and stream a new action-adventure game.",
        category: "gaming",
        brand: "GameMasters",
        income: 9500,
        brandImage: "https://example.com/gamemasters-logo.jpg",
        marketerId: 115,
        dueDate: "2025-04-20",
        influencerCount: 3,
        minimumFollower: 40000
    },
    {
        jobId: 16,
        title: "Sports Influencer for Outdoor Adventure Gear",
        description: "Create content about the latest outdoor adventure gear.",
        category: "sport",
        brand: "OutdoorX",
        income: 6500,
        brandImage: "https://example.com/outdoorx-logo.jpg",
        marketerId: 116,
        dueDate: "2025-05-01",
        influencerCount: 5,
        minimumFollower: 15000
    },
    {
        jobId: 17,
        title: "Fashion Blogger for Winter Wardrobe Essentials",
        description: "Promote winter wardrobe essentials on your blog and social media.",
        category: "fashion",
        brand: "CoolStyle",
        income: 5300,
        brandImage: "https://example.com/coolstyle-logo.jpg",
        marketerId: 117,
        dueDate: "2025-11-15",
        influencerCount: 5,
        minimumFollower: 14000
    },
    {
        jobId: 18,
        title: "Tech Influencer for Smart Home Gadgets",
        description: "Showcase and review new smart home devices.",
        category: "tech",
        brand: "SmartTech",
        income: 8500,
        brandImage: "https://example.com/smarttech-logo.jpg",
        marketerId: 118,
        dueDate: "2025-04-10",
        influencerCount: 2,
        minimumFollower: 25000
    },
    {
        jobId: 19,
        title: "Beauty Blogger for Hair Care Products",
        description: "Promote a new line of hair care products.",
        category: "beauty",
        brand: "HairCarePro",
        income: 5900,
        brandImage: "https://example.com/haircarepro-logo.jpg",
        marketerId: 119,
        dueDate: "2025-04-30",
        influencerCount: 4,
        minimumFollower: 15000
    },
    {
        jobId: 20,
        title: "Lifestyle Influencer for Work-Life Balance",
        description: "Create content about maintaining a healthy work-life balance.",
        category: "lifestyle",
        brand: "BalanceLife",
        income: 4100,
        brandImage: "https://example.com/balancelife-logo.jpg",
        marketerId: 120,
        dueDate: "2025-01-30",
        influencerCount: 8,
        minimumFollower: 12000
    },
    {
        jobId: 21,
        title: "Food Blogger for Baking Series",
        description: "Share baking recipes and tips in a video series.",
        category: "food",
        brand: "BakeMaster",
        income: 5200,
        brandImage: "https://example.com/bakemaster-logo.jpg",
        marketerId: 121,
        dueDate: "2024-12-25",
        influencerCount: 5,
        minimumFollower: 5000
    }
]
